### PR TITLE
Refactoring of the configuration docs

### PR DESCRIPTION
**Pull request by funkyfuture**
this pr is a proposal for a restructured documentation on configuration. there are no amendments in regards to missing parameters yet. it's a wip state to get feedback on the overall structure.

[rendered view](https://github.com/telota/digilib/blob/config_docs/doc/src/site/markdown/digilib-config.md)

adresses #4.

### CODE REVIEW

**Comment by funkyfuture** [comment]
@robcast can you give me a short feedback whether i should continue on this path? i'd have some time for it atm.

**Comment by robcast** [comment]
Yes, please continue if you have some time. I like the more structured page.
I can also fill in detail information but I am not sure when I will be able to do so.

**Comment by funkyfuture** [comment]
okay, i amended everything i could find. there are several **TODO**s and one **FIXME?** annotations where i'm clueless.

cc @schnoepf @notand, you migth be interested in this.

**Comment by notand** [comment]
@funkyfuture Thanks, very helpful, especially the link how to view the config.

**Pull request merged**
